version: '3.8'

services:
  mongodb:
    image: mongo:latest
    restart: always
    container_name: mongodb-wefox-challenge
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: admin
      MONGO_INITDB_DATABASE: wefox
    ports:
      - 27017:27017
    volumes:
      - ./mongodb/data:/data/db